### ISSUE TITLE
Release 0.0.0 without any code

### ISSUE THREAD

**Issue by brotbert** [joshdk/ykmango#9]
When using `glide` it asks for using the release `0.0.0`:

```
[INFO]	Attempting to get package github.com/joshdk/ykmango
[INFO]	--> Gathering release information for github.com/joshdk/ykmango
[INFO]	The package github.com/joshdk/ykmango appears to have Semantic Version releases (http://semver.org).
[INFO]	The latest release is 0.0.0. You are currently not using a release. Would you like
[INFO]	to use this release? Yes (Y) or No (N)
```

Unfortunately `0.0.0` [does not contain any code](https://github.com/joshdk/ykmango/tree/0.0.0).

Can you please retract and re-release? Thanks!

**Comment by joshdk** [comment]
Hello @brotbert,

The `0.0.0` tag exists on a empty ref (`git commit --allow-empty -m 'Initial commit'`) at the beginning of history. I do this so that `git describe --tags` always works, wherever you happen to be in the git history.

I've updated the "release" in GitHub and marked it as a "Pre-release"; I'm not sure if Glide pays attention to things like that (probably not). A proper solution would be for me to cut an additional release.

**Comment by joshdk** [comment]
I've gone and tagged a [`0.1.0` release](https://github.com/joshdk/ykmango/releases/tag/0.1.0) for you @brotbert. Let me know if this helps with your Glide setup 🙂

**Comment by brotbert** [comment]
Thanks @joshdk, I really appreciate this!
